//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelper.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Acceleration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t connect to ASUS ACPI. Application can&apos;t function without it. Try to install Asus System Control Interface benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ACPIError {
            get {
                return ResourceManager.GetString("ACPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart your device to apply changes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertAPUMemoryRestart {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart now? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertAPUMemoryRestartTitle {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks like GPU is in heavy use, disable it? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertDGPU {
            get {
                return ResourceManager.GetString("AlertDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eco Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertDGPUTitle {
            get {
                return ResourceManager.GetString("AlertDGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switching off Ultimate Mode requires restart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertUltimateOff {
            get {
                return ResourceManager.GetString("AlertUltimateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ultimate Mode requires restart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertUltimateOn {
            get {
                return ResourceManager.GetString("AlertUltimateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reboot now? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AlertUltimateTitle {
            get {
                return ResourceManager.GetString("AlertUltimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ally Controller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AllyController {
            get {
                return ResourceManager.GetString("AllyController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ambient mode may increase resource usage benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AmbientModeResources {
            get {
                return ResourceManager.GetString("AmbientModeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Animation Speed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AnimationSpeed {
            get {
                return ResourceManager.GetString("AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anime Matrix benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AnimeMatrix {
            get {
                return ResourceManager.GetString("AnimeMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App already running benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G-Helper is already running. Check system tray for an icon. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AppAlreadyRunningText {
            get {
                return ResourceManager.GetString("AppAlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Custom Fan Curve benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyFanCurve {
            get {
                return ResourceManager.GetString("ApplyFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Power Limits benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyPowerLimits {
            get {
                return ResourceManager.GetString("ApplyPowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto adjust Windows Power Modes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ApplyWindowsPowerPlan {
            get {
                return ResourceManager.GetString("ApplyWindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory Assigned to GPU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string APUMemory {
            get {
                return ResourceManager.GetString("APUMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Asus Services Running benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AsusServicesRunning {
            get {
                return ResourceManager.GetString("AsusServicesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery State benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraBatteryState {
            get {
                return ResourceManager.GetString("AuraBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Breathe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraBreathe {
            get {
                return ResourceManager.GetString("AuraBreathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clockwise benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraClockwise {
            get {
                return ResourceManager.GetString("AuraClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Cycle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraColorCycle {
            get {
                return ResourceManager.GetString("AuraColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraComet {
            get {
                return ResourceManager.GetString("AuraComet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Counterclockwise benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraCounterClockwise {
            get {
                return ResourceManager.GetString("AuraCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraFast {
            get {
                return ResourceManager.GetString("AuraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lighting Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraLightingMode {
            get {
                return ResourceManager.GetString("AuraLightingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraNormal {
            get {
                return ResourceManager.GetString("AuraNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rainbow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraRainbow {
            get {
                return ResourceManager.GetString("AuraRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraRandomColor {
            get {
                return ResourceManager.GetString("AuraRandomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   React benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraReact {
            get {
                return ResourceManager.GetString("AuraReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraSlow {
            get {
                return ResourceManager.GetString("AuraSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraStatic {
            get {
                return ResourceManager.GetString("AuraStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strobe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraStrobe {
            get {
                return ResourceManager.GetString("AuraStrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraZoneAll {
            get {
                return ResourceManager.GetString("AuraZoneAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dock benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraZoneDock {
            get {
                return ResourceManager.GetString("AuraZoneDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraZoneLogo {
            get {
                return ResourceManager.GetString("AuraZoneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrollwheel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraZoneScroll {
            get {
                return ResourceManager.GetString("AuraZoneScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underglow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AuraZoneUnderglow {
            get {
                return ResourceManager.GetString("AuraZoneUnderglow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Apply benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets 60Hz to save battery, and back when plugged benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AutoRefreshTooltip {
            get {
                return ResourceManager.GetString("AutoRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Awake benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Awake {
            get {
                return ResourceManager.GetString("Awake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightLow {
            get {
                return ResourceManager.GetString("BacklightLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightMax {
            get {
                return ResourceManager.GetString("BacklightMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightMid {
            get {
                return ResourceManager.GetString("BacklightMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightOff {
            get {
                return ResourceManager.GetString("BacklightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout plugged / on battery (0 - ON) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightTimeout {
            get {
                return ResourceManager.GetString("BacklightTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backlight Timeout when on battery benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightTimeoutBattery {
            get {
                return ResourceManager.GetString("BacklightTimeoutBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backlight Timeout when plugged benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BacklightTimeoutPlugged {
            get {
                return ResourceManager.GetString("BacklightTimeoutPlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Balanced benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charge benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BatteryCharge {
            get {
                return ResourceManager.GetString("BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery Charge Limit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BatteryChargeLimit {
            get {
                return ResourceManager.GetString("BatteryChargeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery Health benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One time charge to 100% benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BatteryLimitFull {
            get {
                return ResourceManager.GetString("BatteryLimitFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binding benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BindingPrimary {
            get {
                return ResourceManager.GetString("BindingPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secondary benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BindingSecondary {
            get {
                return ResourceManager.GetString("BindingSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BIOS and Driver Updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BiosAndDriverUpdates {
            get {
                return ResourceManager.GetString("BiosAndDriverUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boot Sound benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BootSound {
            get {
                return ResourceManager.GetString("BootSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness Down benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BrightnessDown {
            get {
                return ResourceManager.GetString("BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness Up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BrightnessUp {
            get {
                return ResourceManager.GetString("BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black and white tray icon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BWTrayIcon {
            get {
                return ResourceManager.GetString("BWTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Calibrate {
            get {
                return ResourceManager.GetString("Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charging benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contrast benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Controller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU Boost benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CPUBoost {
            get {
                return ResourceManager.GetString("CPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deceleration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Deceleration {
            get {
                return ResourceManager.GetString("Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Controller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DisableController {
            get {
                return ResourceManager.GetString("DisableController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please disable Windows &gt; Dynamic Lighting benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DisableDynamicLighting {
            get {
                return ResourceManager.GetString("DisableDynamicLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable on lid close benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DisableOnLidClose {
            get {
                return ResourceManager.GetString("DisableOnLidClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable screen overdrive benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DisableOverdrive {
            get {
                return ResourceManager.GetString("DisableOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharging benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Color Profiles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DownloadColorProfiles {
            get {
                return ResourceManager.GetString("DownloadColorProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drivers and Software benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DriverAndSoftware {
            get {
                return ResourceManager.GetString("DriverAndSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disables dGPU to save battery benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EcoGPUTooltip {
            get {
                return ResourceManager.GetString("EcoGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eco benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EcoMode {
            get {
                return ResourceManager.GetString("EcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable GPU on shutdown (prevents issue with Eco mode) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnableGPUOnShutdown {
            get {
                return ResourceManager.GetString("EnableGPUOnShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabling the dGPU by going into Eco mode while Display Mode in NVIDIA Control Panel is not set to Optimus might cause problems with brightness controls until after the next reboot. 
        ///
        ///Do you still want to continue? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnableOptimusText {
            get {
                return ResourceManager.GetString("EnableOptimusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NVIDIA Display Mode is not set to Optimus benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnableOptimusTitle {
            get {
                return ResourceManager.GetString("EnableOptimusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Energy Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnergySettings {
            get {
                return ResourceManager.GetString("EnergySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extra Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ExtraSettings {
            get {
                return ResourceManager.GetString("ExtraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Factory Defaults benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FactoryDefaults {
            get {
                return ResourceManager.GetString("FactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan Curves benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanCurves {
            get {
                return ResourceManager.GetString("FanCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU Fan Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanProfileCPU {
            get {
                return ResourceManager.GetString("FanProfileCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU Fan Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanProfileGPU {
            get {
                return ResourceManager.GetString("FanProfileGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mid Fan Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanProfileMid {
            get {
                return ResourceManager.GetString("FanProfileMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan Profiles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanProfiles {
            get {
                return ResourceManager.GetString("FanProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fans and Power benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FansAndPower {
            get {
                return ResourceManager.GetString("FansAndPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fans + Power benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FansPower {
            get {
                return ResourceManager.GetString("FansPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flicker-free Dimming benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FlickerFreeDimming {
            get {
                return ResourceManager.GetString("FlickerFreeDimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Fn+F hotkeys without Fn benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FnLock {
            get {
                return ResourceManager.GetString("FnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FN-Lock Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FnLockOff {
            get {
                return ResourceManager.GetString("FnLockOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FN-Lock On benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FnLockOn {
            get {
                return ResourceManager.GetString("FnLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dynamic Boost benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUBoost {
            get {
                return ResourceManager.GetString("GPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUChanging {
            get {
                return ResourceManager.GetString("GPUChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Core Clock Offset benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUCoreClockOffset {
            get {
                return ResourceManager.GetString("GPUCoreClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory Clock Offset benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUMemoryClockOffset {
            get {
                return ResourceManager.GetString("GPUMemoryClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUMode {
            get {
                return ResourceManager.GetString("GPUMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iGPU only benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUModeEco {
            get {
                return ResourceManager.GetString("GPUModeEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iGPU + dGPU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUModeStandard {
            get {
                return ResourceManager.GetString("GPUModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dGPU exclusive benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUModeUltimate {
            get {
                return ResourceManager.GetString("GPUModeUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU Power benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUPower {
            get {
                return ResourceManager.GetString("GPUPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUSettings {
            get {
                return ResourceManager.GetString("GPUSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature Target benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GPUTempTarget {
            get {
                return ResourceManager.GetString("GPUTempTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minutes till Hibernation in sleep on battery (0 - OFF) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HibernateAfter {
            get {
                return ResourceManager.GetString("HibernateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Rotation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ImageRotation {
            get {
                return ResourceManager.GetString("ImageRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntervalOff {
            get {
                return ResourceManager.GetString("IntervalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval {0}s benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IntervalSeconds {
            get {
                return ResourceManager.GetString("IntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Bindings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KeyBindings {
            get {
                return ResourceManager.GetString("KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop all apps using GPU when switching to Eco benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KillGpuApps {
            get {
                return ResourceManager.GetString("KillGpuApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laptop Backlight benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LaptopBacklight {
            get {
                return ResourceManager.GetString("LaptopBacklight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laptop Keyboard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LaptopKeyboard {
            get {
                return ResourceManager.GetString("LaptopKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Laptop Screen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LaptopScreen {
            get {
                return ResourceManager.GetString("LaptopScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED Status Indicators benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LEDStatusIndicators {
            get {
                return ResourceManager.GetString("LEDStatusIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legend benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t check local version benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LegendGray {
            get {
                return ResourceManager.GetString("LegendGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updated benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LegendGreen {
            get {
                return ResourceManager.GetString("LegendGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Available benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LegendRed {
            get {
                return ResourceManager.GetString("LegendRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lid {
            get {
                return ResourceManager.GetString("Lid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lightbar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lightbar {
            get {
                return ResourceManager.GetString("Lightbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lighting benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock Screen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Stick Deadzones benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LSDeadzones {
            get {
                return ResourceManager.GetString("LSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Trigger Deadzones benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LTDeadzones {
            get {
                return ResourceManager.GetString("LTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio Visualizer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixAudio {
            get {
                return ResourceManager.GetString("MatrixAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary Banner benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixBanner {
            get {
                return ResourceManager.GetString("MatrixBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bright benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixBright {
            get {
                return ResourceManager.GetString("MatrixBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixClock {
            get {
                return ResourceManager.GetString("MatrixClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixDim {
            get {
                return ResourceManager.GetString("MatrixDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rog Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixLogo {
            get {
                return ResourceManager.GetString("MatrixLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixMedium {
            get {
                return ResourceManager.GetString("MatrixMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixOff {
            get {
                return ResourceManager.GetString("MatrixOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MatrixPicture {
            get {
                return ResourceManager.GetString("MatrixPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max refresh rate for lower latency benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MaxRefreshTooltip {
            get {
                return ResourceManager.GetString("MaxRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60Hz refresh rate to save battery benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MinRefreshTooltip {
            get {
                return ResourceManager.GetString("MinRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Angle Snapping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseAngleSnapping {
            get {
                return ResourceManager.GetString("MouseAngleSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Power Off After benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseAutoPowerOff {
            get {
                return ResourceManager.GetString("MouseAutoPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Button Response benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseButtonResponse {
            get {
                return ResourceManager.GetString("MouseButtonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import failed. Selected file is not a valid mouse profile or corrutpted. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseImportFailed {
            get {
                return ResourceManager.GetString("MouseImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lift Off Distance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseLiftOffDistance {
            get {
                return ResourceManager.GetString("MouseLiftOffDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low Battery Warning at benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseLowBatteryWarning {
            get {
                return ResourceManager.GetString("MouseLowBatteryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MousePerformance {
            get {
                return ResourceManager.GetString("MousePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize with mouse benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MouseSynchronize {
            get {
                return ResourceManager.GetString("MouseSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Zone benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Multizone {
            get {
                return ResourceManager.GetString("Multizone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi Zone Strong benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MultizoneStrong {
            get {
                return ResourceManager.GetString("MultizoneStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Muted benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute Mic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MuteMic {
            get {
                return ResourceManager.GetString("MuteMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Never benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NewUpdates {
            get {
                return ResourceManager.GetString("NewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No new updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Connected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One Zone benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OneZone {
            get {
                return ResourceManager.GetString("OneZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open G-Helper window benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenGHelper {
            get {
                return ResourceManager.GetString("OpenGHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimized benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to Eco on battery and to Standard when plugged in benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OptimizedGPUTooltip {
            get {
                return ResourceManager.GetString("OptimizedGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep GPU disabled on USB-C charger in Optimized mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OptimizedUSBC {
            get {
                return ResourceManager.GetString("OptimizedUSBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overdrive benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Peripherals benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Peripherals {
            get {
                return ResourceManager.GetString("Peripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture / Gif benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PictureGif {
            get {
                return ResourceManager.GetString("PictureGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play / Pause benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polling Rate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PollingRate {
            get {
                return ResourceManager.GetString("PollingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Limits benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PowerLimits {
            get {
                return ResourceManager.GetString("PowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Limits is an experimental feature. Use carefully and at your own risk! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PPTExperimental {
            get {
                return ResourceManager.GetString("PPTExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrintScreen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Something is using dGPU and preventing Eco mode. Let G-Helper try to restart dGPU in device manager? (Please proceed at your own risk) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartGPU {
            get {
                return ResourceManager.GetString("RestartGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RPM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Stick Deadzones benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RSDeadzones {
            get {
                return ResourceManager.GetString("RSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Trigger Deadzones benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RTDeadzones {
            get {
                return ResourceManager.GetString("RTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run on Startup benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaling Quality benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScalingQuality {
            get {
                return ResourceManager.GetString("ScalingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenpad Brightness Down benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScreenPadDown {
            get {
                return ResourceManager.GetString("ScreenPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screenpad Brightness Up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScreenPadUp {
            get {
                return ResourceManager.GetString("ScreenPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shutdown benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silent benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery Level benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashBatteryLevel {
            get {
                return ResourceManager.GetString("SlashBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bit Stream benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashBitStream {
            get {
                return ResourceManager.GetString("SlashBitStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bounce benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashBounce {
            get {
                return ResourceManager.GetString("SlashBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buzzer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashBuzzer {
            get {
                return ResourceManager.GetString("SlashBuzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashFlow {
            get {
                return ResourceManager.GetString("SlashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flux benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashFlux {
            get {
                return ResourceManager.GetString("SlashFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Over benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashGameOver {
            get {
                return ResourceManager.GetString("SlashGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hazard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashHazard {
            get {
                return ResourceManager.GetString("SlashHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interfacing benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashInterfacing {
            get {
                return ResourceManager.GetString("SlashInterfacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashLoading {
            get {
                return ResourceManager.GetString("SlashLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slash benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashMode {
            get {
                return ResourceManager.GetString("SlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phantom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashPhantom {
            get {
                return ResourceManager.GetString("SlashPhantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ramp benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashRamp {
            get {
                return ResourceManager.GetString("SlashRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spectrum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashSpectrum {
            get {
                return ResourceManager.GetString("SlashSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashStart {
            get {
                return ResourceManager.GetString("SlashStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashStatic {
            get {
                return ResourceManager.GetString("SlashStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transmission benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlashTransmission {
            get {
                return ResourceManager.GetString("SlashTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sleep benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables dGPU for standard use benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StandardGPUTooltip {
            get {
                return ResourceManager.GetString("StandardGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StandardMode {
            get {
                return ResourceManager.GetString("StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Services benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartingServices {
            get {
                return ResourceManager.GetString("StartingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop GPU Applications benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StopGPUApps {
            get {
                return ResourceManager.GetString("StopGPUApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping Services benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StoppingServices {
            get {
                return ResourceManager.GetString("StoppingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Aura benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleAura {
            get {
                return ResourceManager.GetString("ToggleAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Toggle Clamshell Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleClamshellMode {
            get {
                return ResourceManager.GetString("ToggleClamshellMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Fn-Lock benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleFnLock {
            get {
                return ResourceManager.GetString("ToggleFnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Miniled (if supported) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleMiniled {
            get {
                return ResourceManager.GetString("ToggleMiniled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Screen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleScreen {
            get {
                return ResourceManager.GetString("ToggleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Touchscreen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToggleTouchscreen {
            get {
                return ResourceManager.GetString("ToggleTouchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touchscreen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Touchscreen {
            get {
                return ResourceManager.GetString("Touchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turbo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turned off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable on battery benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TurnOffOnBattery {
            get {
                return ResourceManager.GetString("TurnOffOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routes laptop screen to dGPU, maximizing FPS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UltimateGPUTooltip {
            get {
                return ResourceManager.GetString("UltimateGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ultimate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UltimateMode {
            get {
                return ResourceManager.GetString("UltimateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undervolting is an experimental and risky feature. If applied values are too low for your hardware, it can become unstable, shut down or cause data corruption. If you want to try - start from small values first, click Apply and test what works for you. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UndervoltingRisky {
            get {
                return ResourceManager.GetString("UndervoltingRisky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unmuted benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Unmuted {
            get {
                return ResourceManager.GetString("Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vibration Strength benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VibrationStrength {
            get {
                return ResourceManager.GetString("VibrationStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Modes are not available when HDR is active benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VisualModesHDR {
            get {
                return ResourceManager.GetString("VisualModesHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Modes are not available when laptop screen is off benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VisualModesScreen {
            get {
                return ResourceManager.GetString("VisualModesScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Down benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Mute benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume Up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep app window always on top benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WindowTop {
            get {
                return ResourceManager.GetString("WindowTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
